@PeakPerformance.Api_HostAddress = https://localhost:7117/api/Auth

POST {{PeakPerformance.Api_HostAddress}}/Registration/
Accept: application/json
Content-Type: application/json

{
  "fullName": "TEST",
  "username": "TEST",
  "email": "test@test.com",
  "password": "",
  "confirmPassword": "",
  "dateOfBirth": "2002-10-10"
}

###

POST {{PeakPerformance.Api_HostAddress}}/Login/
Accept: application/json
Content-Type: application/json

{
  "username": "TEST",
  "password": ""
}

###
