SET IDENTITY_INSERT Country ON;

INSERT INTO Country (Id, ISO2, ISO3, Name) VALUES
(1, N'AF', N'AFG', N'Afghanistan'),
(2, N'AX', N'ALA', N'Aland Islands'),
(3, N'AL', N'ALB', N'Albania'),
(4, N'DZ', N'DZA', N'Algeria'),
(5, N'AS', N'ASM', N'American Samoa'),
(6, N'AD', N'AND', N'Andorra'),
(7, N'AO', N'AGO', N'Angola'),
(8, N'AI', N'AIA', N'Anguilla'),
(9, N'AQ', N'ATA', N'Antarctica'),
(10, N'AG', N'ATG', N'Antigua and Barbuda'),
(11, N'AR', N'ARG', N'Argentina'),
(12, N'AM', N'ARM', N'Armenia'),
(13, N'AW', N'ABW', N'Aruba'),
(14, N'AU', N'AUS', N'Australia'),
(15, N'AT', N'AUT', N'Austria'),
(16, N'AZ', N'AZE', N'Azerbaijan'),
(17, N'BS', N'BHS', N'Bahamas'),
(18, N'BH', N'BHR', N'Bahrain'),
(19, N'BD', N'BGD', N'Bangladesh'),
(20, N'BB', N'BRB', N'Barbados'),
(21, N'BY', N'BLR', N'Belarus'),
(22, N'BE', N'BEL', N'Belgium'),
(23, N'BZ', N'BLZ', N'Belize'),
(24, N'BJ', N'BEN', N'Benin'),
(25, N'BM', N'BMU', N'Bermuda'),
(26, N'BT', N'BTN', N'Bhutan'),
(27, N'BO', N'BOL', N'Bolivia'),
(28, N'BQ', N'BES', N'Bonaire'),
(29, N'BA', N'BIH', N'Bosnia and Herzegovina'),
(30, N'BW', N'BWA', N'Botswana'),
(31, N'BV', N'BVT', N'Bouvet Island'),
(32, N'BR', N'BRA', N'Brazil'),
(33, N'IO', N'IOT', N'British Indian Ocean Territory'),
(34, N'BN', N'BRN', N'Brunei Darussalam'),
(35, N'BG', N'BGR', N'Bulgaria'),
(36, N'BF', N'BFA', N'Burkina Faso'),
(37, N'BI', N'BDI', N'Burundi'),
(38, N'CV', N'CPV', N'Cabo Verde'),
(39, N'KH', N'KHM', N'Cambodia'),
(40, N'CM', N'CMR', N'Cameroon'),
(41, N'CA', N'CAN', N'Canada'),
(42, N'KY', N'CYM', N'Cayman Islands'),
(43, N'CF', N'CAF', N'Central African Republic'),
(44, N'TD', N'TCD', N'Chad'),
(45, N'CL', N'CHL', N'Chile'),
(46, N'CN', N'CHN', N'China'),
(47, N'CX', N'CXR', N'Christmas Island'),
(48, N'CC', N'CCK', N'Cocos Islands'),
(49, N'CO', N'COL', N'Colombia'),
(50, N'KM', N'COM', N'Comoros'),
(51, N'CD', N'COD', N'Democratic Republic of the Congo'),
(52, N'CG', N'COG', N'Congo'),
(53, N'CK', N'COK', N'Cook Islands'),
(54, N'CR', N'CRI', N'Costa Rica'),
(55, N'HR', N'HRV', N'Croatia'),
(56, N'CU', N'CUB', N'Cuba'),
(57, N'CW', N'CUW', N'Cura‡ao'),
(58, N'CY', N'CYP', N'Cyprus'),
(59, N'CZ', N'CZE', N'Czechia'),
(60, N'CI', N'CIV', N'C“te d''Ivoire'),
(61, N'DK', N'DNK', N'Denmark'),
(62, N'DJ', N'DJI', N'Djibouti'),
(63, N'DM', N'DMA', N'Dominica'),
(64, N'DO', N'DOM', N'Dominican Republic'),
(65, N'EC', N'ECU', N'Ecuador'),
(66, N'EG', N'EGY', N'Egypt'),
(67, N'SV', N'SLV', N'El Salvador'),
(68, N'GQ', N'GNQ', N'Equatorial Guinea'),
(69, N'ER', N'ERI', N'Eritrea'),
(70, N'EE', N'EST', N'Estonia'),
(71, N'SZ', N'SWZ', N'Eswatini'),
(72, N'ET', N'ETH', N'Ethiopia'),
(73, N'FK', N'FLK', N'Falkland Islands'),
(74, N'FO', N'FRO', N'Faroe Islands'),
(75, N'FJ', N'FJI', N'Fiji'),
(76, N'FI', N'FIN', N'Finland'),
(77, N'FR', N'FRA', N'France'),
(78, N'GF', N'GUF', N'French Guiana'),
(79, N'PF', N'PYF', N'French Polynesia'),
(80, N'TF', N'ATF', N'French Southern Territories'),
(81, N'GA', N'GAB', N'Gabon'),
(82, N'GM', N'GMB', N'Gambia'),
(83, N'GE', N'GEO', N'Georgia'),
(84, N'DE', N'DEU', N'Germany'),
(85, N'GH', N'GHA', N'Ghana'),
(86, N'GI', N'GIB', N'Gibraltar'),
(87, N'GR', N'GRC', N'Greece'),
(88, N'GL', N'GRL', N'Greenland'),
(89, N'GD', N'GRD', N'Grenada'),
(90, N'GP', N'GLP', N'Guadeloupe'),
(91, N'GU', N'GUM', N'Guam'),
(92, N'GT', N'GTM', N'Guatemala'),
(93, N'GG', N'GGY', N'Guernsey'),
(94, N'GN', N'GIN', N'Guinea'),
(95, N'GW', N'GNB', N'Guinea-Bissau'),
(96, N'GY', N'GUY', N'Guyana'),
(97, N'HT', N'HTI', N'Haiti'),
(98, N'HM', N'HMD', N'Heard Island and McDonald Islands'),
(99, N'VA', N'VAT', N'Vatican'),
(100, N'HN', N'HND', N'Honduras'),
(101, N'HK', N'HKG', N'Hong Kong'),
(102, N'HU', N'HUN', N'Hungary'),
(103, N'IS', N'ISL', N'Iceland'),
(104, N'IN', N'IND', N'India'),
(105, N'ID', N'IDN', N'Indonesia'),
(106, N'IR', N'IRN', N'Iran'),
(107, N'IQ', N'IRQ', N'Iraq'),
(108, N'IE', N'IRL', N'Ireland'),
(109, N'IM', N'IMN', N'Isle of Man'),
(110, N'IL', N'ISR', N'Israel'),
(111, N'IT', N'ITA', N'Italy'),
(112, N'JM', N'JAM', N'Jamaica'),
(113, N'JP', N'JPN', N'Japan'),
(114, N'JE', N'JEY', N'Jersey'),
(115, N'JO', N'JOR', N'Jordan'),
(116, N'KZ', N'KAZ', N'Kazakhstan'),
(117, N'KE', N'KEN', N'Kenya'),
(118, N'KI', N'KIR', N'Kiribati'),
(119, N'KP', N'PRK', N'North Korea'),
(120, N'KR', N'KOR', N'South Korea'),
(121, N'KW', N'KWT', N'Kuwait'),
(122, N'KG', N'KGZ', N'Kyrgyzstan'),
(123, N'LA', N'LAO', N'Laos'),
(124, N'LV', N'LVA', N'Latvia'),
(125, N'LB', N'LBN', N'Lebanon'),
(126, N'LS', N'LSO', N'Lesotho'),
(127, N'LR', N'LBR', N'Liberia'),
(128, N'LY', N'LBY', N'Libya'),
(129, N'LI', N'LIE', N'Liechtenstein'),
(130, N'LT', N'LTU', N'Lithuania'),
(131, N'LU', N'LUX', N'Luxembourg'),
(132, N'MO', N'MAC', N'Macao'),
(133, N'MG', N'MDG', N'Madagascar'),
(134, N'MW', N'MWI', N'Malawi'),
(135, N'MY', N'MYS', N'Malaysia'),
(136, N'MV', N'MDV', N'Maldives'),
(137, N'ML', N'MLI', N'Mali'),
(138, N'MT', N'MLT', N'Malta'),
(139, N'MH', N'MHL', N'Marshall Islands'),
(140, N'MQ', N'MTQ', N'Martinique'),
(141, N'MR', N'MRT', N'Mauritania'),
(142, N'MU', N'MUS', N'Mauritius'),
(143, N'YT', N'MYT', N'Mayotte'),
(144, N'MX', N'MEX', N'Mexico'),
(145, N'FM', N'FSM', N'Micronesia'),
(146, N'MD', N'MDA', N'Moldova'),
(147, N'MC', N'MCO', N'Monaco'),
(148, N'MN', N'MNG', N'Mongolia'),
(149, N'ME', N'MNE', N'Montenegro'),
(150, N'MS', N'MSR', N'Montserrat'),
(151, N'MA', N'MAR', N'Morocco'),
(152, N'MZ', N'MOZ', N'Mozambique'),
(153, N'MM', N'MMR', N'Myanmar'),
(154, N'NA', N'NAM', N'Namibia'),
(155, N'NR', N'NRU', N'Nauru'),
(156, N'NP', N'NPL', N'Nepal'),
(157, N'NL', N'NLD', N'Netherlands'),
(158, N'NC', N'NCL', N'New Caledonia'),
(159, N'NZ', N'NZL', N'New Zealand'),
(160, N'NI', N'NIC', N'Nicaragua'),
(161, N'NE', N'NER', N'Niger'),
(162, N'NG', N'NGA', N'Nigeria'),
(163, N'NU', N'NIU', N'Niue'),
(164, N'NF', N'NFK', N'Norfolk Island'),
(165, N'MP', N'MNP', N'Northern Mariana Islands'),
(166, N'NO', N'NOR', N'Norway'),
(167, N'OM', N'OMN', N'Oman'),
(168, N'PK', N'PAK', N'Pakistan'),
(169, N'PW', N'PLW', N'Palau'),
(170, N'PS', N'PSE', N'Palestine'),
(171, N'PA', N'PAN', N'Panama'),
(172, N'PG', N'PNG', N'Papua New Guinea'),
(173, N'PY', N'PRY', N'Paraguay'),
(174, N'PE', N'PER', N'Peru'),
(175, N'PH', N'PHL', N'Philippines'),
(176, N'PN', N'PCN', N'Pitcairn'),
(177, N'PL', N'POL', N'Poland'),
(178, N'PT', N'PRT', N'Portugal'),
(179, N'PR', N'PRI', N'Puerto Rico'),
(180, N'QA', N'QAT', N'Qatar'),
(181, N'MK', N'MKD', N'Republic of North Macedonia'),
(182, N'RO', N'ROU', N'Romania'),
(183, N'RU', N'RUS', N'Russian Federation'),
(184, N'RW', N'RWA', N'Rwanda'),
(185, N'RE', N'REU', N'Reunion'),
(186, N'BL', N'BLM', N'Saint Barthelemy'),
(187, N'SH', N'SHN', N'Saint Helena'),
(188, N'KN', N'KNA', N'Saint Kitts and Nevis'),
(189, N'LC', N'LCA', N'Saint Lucia'),
(190, N'MF', N'MAF', N'Saint Martin'),
(191, N'PM', N'SPM', N'Saint Pierre and Miquelon'),
(192, N'VC', N'VCT', N'Saint Vincent and the Grenadines'),
(193, N'WS', N'WSM', N'Samoa'),
(194, N'SM', N'SMR', N'San Marino'),
(195, N'ST', N'STP', N'Sao Tome and Principe'),
(196, N'SA', N'SAU', N'Saudi Arabia'),
(197, N'SN', N'SEN', N'Senegal'),
(198, N'RS', N'SRB', N'Serbia'),
(199, N'SC', N'SYC', N'Seychelles'),
(200, N'SL', N'SLE', N'Sierra Leone'),
(201, N'SG', N'SGP', N'Singapore'),
(202, N'SX', N'SXM', N'Sint Maarten'),
(203, N'SK', N'SVK', N'Slovakia'),
(204, N'SI', N'SVN', N'Slovenia'),
(205, N'SB', N'SLB', N'Solomon Islands'),
(206, N'SO', N'SOM', N'Somalia'),
(207, N'ZA', N'ZAF', N'South Africa'),
(208, N'GS', N'SGS', N'South Georgia and the South Sandwich Islands'),
(209, N'SS', N'SSD', N'South Sudan'),
(210, N'ES', N'ESP', N'Spain'),
(211, N'LK', N'LKA', N'Sri Lanka'),
(212, N'SD', N'SDN', N'Sudan'),
(213, N'SR', N'SUR', N'Suriname'),
(214, N'SJ', N'SJM', N'Svalbard and Jan Mayen'),
(215, N'SE', N'SWE', N'Sweden'),
(216, N'CH', N'CHE', N'Switzerland'),
(217, N'SY', N'SYR', N'Syrian Arab Republic'),
(218, N'TW', N'TWN', N'Taiwan'),
(219, N'TJ', N'TJK', N'Tajikistan'),
(220, N'TZ', N'TZA', N'Tanzania'),
(221, N'TH', N'THA', N'Thailand'),
(222, N'TL', N'TLS', N'Timor-Leste'),
(223, N'TG', N'TGO', N'Togo'),
(224, N'TK', N'TKL', N'Tokelau'),
(225, N'TO', N'TON', N'Tonga'),
(226, N'TT', N'TTO', N'Trinidad and Tobago'),
(227, N'TN', N'TUN', N'Tunisia'),
(228, N'TR', N'TUR', N'Turkey'),
(229, N'TM', N'TKM', N'Turkmenistan'),
(230, N'TC', N'TCA', N'Turks and Caicos Islands'),
(231, N'TV', N'TUV', N'Tuvalu'),
(232, N'UG', N'UGA', N'Uganda'),
(233, N'UA', N'UKR', N'Ukraine'),
(234, N'AE', N'ARE', N'United Arab Emirates'),
(235, N'GB', N'GBR', N'United Kingdom'),
(236, N'UM', N'UMI', N'United States Minor Outlying Islands'),
(237, N'US', N'USA', N'United States of America'),
(238, N'UY', N'URY', N'Uruguay'),
(239, N'UZ', N'UZB', N'Uzbekistan'),
(240, N'VU', N'VUT', N'Vanuatu'),
(241, N'VE', N'VEN', N'Venezuela'),
(242, N'VN', N'VNM', N'Viet Nam'),
(243, N'VG', N'VGB', N'British Virgin Islands'),
(244, N'VI', N'VIR', N'U.S. Virgin Islands'),
(245, N'WF', N'WLF', N'Wallis and Futuna'),
(246, N'EH', N'ESH', N'Western Sahara'),
(247, N'YE', N'YEM', N'Yemen'),
(248, N'ZM', N'ZMB', N'Zambia'),
(249, N'ZW', N'ZWE', N'Zimbabwe');

SET IDENTITY_INSERT Country OFF;